In [34]:
#Import importent library
import seaborn as sns
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
#3D visualization
import plotly.express as px

In [3]:
haberman=pd.read_csv("haberman.csv")

In [4]:
haberman

Age_of_patient_at_time_of_operation  Patients_year_of_operation  \
0                                     30                          64   
1                                     30                          62   
2                                     30                          65   
3                                     31                          59   
4                                     31                          65   
..                                   ...                         ...   
301                                   75                          62   
302                                   76                          67   
303                                   77                          65   
304                                   78                          65   
305                                   83                          58   

     Number_of_positive_axillary_nodes_detected  Survival_status  
0                                             1                1  
1                                             3                1  
2                                             0                1  
3                                             2                1  
4                                             4                1  
..                                          ...              ...  
301                                           1                1  
302                                           0                1  
303                                           3                1  
304                                           1                2  
305                                           2                2  

[306 rows x 4 columns]

In [5]:
haberman.head()

Age_of_patient_at_time_of_operation  Patients_year_of_operation  \
0                                   30                          64   
1                                   30                          62   
2                                   30                          65   
3                                   31                          59   
4                                   31                          65   

   Number_of_positive_axillary_nodes_detected  Survival_status  
0                                           1                1  
1                                           3                1  
2                                           0                1  
3                                           2                1  
4                                           4                1

In [7]:
haberman.tail()

Age_of_patient_at_time_of_operation  Patients_year_of_operation  \
301                                   75                          62   
302                                   76                          67   
303                                   77                          65   
304                                   78                          65   
305                                   83                          58   

     Number_of_positive_axillary_nodes_detected  Survival_status  
301                                           1                1  
302                                           0                1  
303                                           3                1  
304                                           1                2  
305                                           2                2

In [11]:
haberman.columns=['age','year','axillary_nodes','survive_status']

In [12]:
df=pd.DataFrame(haberman,columns=haberman.columns)

In [13]:
df

age  year  axillary_nodes  survive_status
0     30    64               1               1
1     30    62               3               1
2     30    65               0               1
3     31    59               2               1
4     31    65               4               1
..   ...   ...             ...             ...
301   75    62               1               1
302   76    67               0               1
303   77    65               3               1
304   78    65               1               2
305   83    58               2               2

[306 rows x 4 columns]

In [17]:
x=df[['age','year','axillary_nodes','survive_status']]
y=df['survive_status']

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [21]:
x_train.shape

(306, 4)

In [22]:
x_test.shape

(306,)

In [24]:
y_train.shape

(244,)

In [25]:
y_test.shape

(62,)

In [26]:
neigh=KNeighborsClassifier(n_neighbors=21)

In [27]:
neigh

KNeighborsClassifier(n_neighbors=21)

In [28]:
neigh.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=21)

In [29]:
y_pred_train=neigh.predict(x_train)
y_pred_test=neigh.predict(x_test)

In [30]:
y_pred_train

array([1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
       2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 1])

In [31]:
y_pred_test

array([1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1,
       1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1])

In [35]:
acc_test=accuracy_score(y_pred_test,y_test)

In [36]:
acc_test

0.6935483870967742

In [37]:
acc_train=accuracy_score(y_pred_train,y_train)

In [38]:
acc_train

0.7786885245901639

In [ ]:
from sklearn.metrics import classification_

# confusion metric

In [54]:
from sklearn.metrics import classification_report
t=['1','2']
print(classification_report(y_test,y_pred_test,target_names=t))

              precision    recall  f1-score   support

           1       0.74      0.89      0.80        44
           2       0.44      0.22      0.30        18

    accuracy                           0.69        62
   macro avg       0.59      0.55      0.55        62
weighted avg       0.65      0.69      0.66        62



In [46]:
y_test.value_counts()

1    44
2    18
Name: survive_status, dtype: int64

In [47]:
y_train.value_counts()

1    181
2     63
Name: survive_status, dtype: int64

In [52]:
from sklearn.metrics import confusion_matrix

In [53]:
confusion_matrix(y_test,y_pred_test)

array([[39,  5],
       [14,  4]])

In [56]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_data = scaler.fit_transform(df)

In [57]:
scaled_data

array([[-2.08214014,  0.35358406, -0.42159203, -0.6       ],
       [-2.08214014, -0.26292148, -0.14295885, -0.6       ],
       [-2.08214014,  0.66183684, -0.56090862, -0.6       ],
       ...,
       [ 2.2754471 ,  0.66183684, -0.14295885, -0.6       ],
       [ 2.36816172,  0.66183684, -0.42159203,  1.66666667],
       [ 2.83173483, -1.49593258, -0.28227544,  1.66666667]])

In [60]:
scaled_data = scaler.fit_transform([[10,20,100]])

In [63]:
scaled_data

array([[0., 0., 0.]])

In [65]:
lst=np.array([[10,20,100],[10,80,100]])
scaler.fit_transform(lst)

array([[ 0., -1.,  0.],
       [ 0.,  1.,  0.]])

In [69]:
from sklearn.preprocessing import StandardScaler
data = [[0, 0], [0, 0], [1, 1], [5, 5]]
scaler = StandardScaler()
print(scaler.fit_transform(data))

[[-0.72760688 -0.72760688]
 [-0.72760688 -0.72760688]
 [-0.24253563 -0.24253563]
 [ 1.69774938  1.69774938]]
