# Numpy as np


In [26]:
#crate a array using numpy
import numpy as np
x=np.array([[1,2,3],[2,4,9]])
y=np.array([[1,2,3],[2,4,9]])
print("x :\n",x)
print("y :\n",y)
print()
add = x+y
print("add :\n",add)
sub = x-y
print("sub :\n",sub)
mul=x*y
print("product :\n",mul)
div=x/y
print("Divide :\n",div)

x :
 [[1 2 3]
 [2 4 9]]
y :
 [[1 2 3]
 [2 4 9]]

add :
 [[ 2  4  6]
 [ 4  8 18]]
sub :
 [[0 0 0]
 [0 0 0]]
product :
 [[ 1  4  9]
 [ 4 16 81]]
Divide :
 [[1. 1. 1.]
 [1. 1. 1.]]


In [25]:
# Numpy array index
import numpy as np
m=[[10,20,3,0],[5,25,15,12]]
matrix=np.array(m)
print(matrix[0][0])
print(matrix[0][2])
print(matrix[1][0])
print(matrix[1][2])

10
3
5
15


In [31]:
import numpy as np
def create_matrix(m):
    mx=np.array(m)
    print("Matrix :\n",mx)
    
create_matrix([[1,0,0],[0,1,0],[0,0,1]])    

Matrix :
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [42]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0][0,2])


3


# Accelerated operations

pandas has support for accelerating certain types of binary numerical and boolean operations using the numexpr library and the bottleneck libraries.

These libraries are especially useful when dealing with large data sets, and provide large speedups. numexpr uses smart chunking, caching, and multiple cores. bottleneck is a set of specialized cython routines that are especially fast when dealing with arrays that have nans.

pd.set_option("compute.use_bottleneck", False)
pd.set_option("compute.use_numexpr", False)

In [1]:
pd.set_option("compute.use_bottleneck",False)
pd.set_option("compute.use_numexpr",False)

NameError: name 'pd' is not defined