# Numpy as np

There are 6 general mechanisms for creating arrays:

    1. Conversion from other Python structures (i.e. lists and tuples)
    2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)
    3. Replicating, joining, or mutating existing arrays
    4. Reading arrays from disk, either from standard or custom formats
    5. Creating arrays from raw bytes through the use of strings or buffers
    6. Use of special library functions (e.g., random)
    

In [2]:
#NumPy Creating Arrays
import numpy as np
arr=[[20,15,10],[10,20,30]]
x=np.array(arr)
print("x :\n",x)

x :
 [[20 15 10]
 [10 20 30]]


In [18]:
#user input and create a matrix
import numpy as np
def create_matrix(mat):
    x=np.array(mat)
    return x
def main():
    matrix=[[50,30,12],[45,33,20],[10,15,9]]
    ans=create_matrix(matrix)
    print("x :")
    print(ans,end="\n\n")
    print(f"{ans[1][2]} + {ans[1][2]} : {ans[1][2]+ans[1][2]}")
if __name__:='__main__':
        main()


x :
[[50 30 12]
 [45 33 20]
 [10 15  9]]

20 + 20 : 40


In [7]:
import numpy as np
a = np.array([10,5,15,20,11])
print(a)
print(type(a))
arr = np.array({1, 2, 3, 4, 5})
print(arr)
print(type(arr))

[10  5 15 20 11]
<class 'numpy.ndarray'>
{1, 2, 3, 4, 5}
<class 'numpy.ndarray'>


In [18]:
import numpy as np
matrix=np.array([[10,20,30,],[10,30,20]])
print(matrix)


[[10 20 30]
 [10 30 20]]


In [27]:
import numpy as np
matrix=n.array([[10,20,30,],[10,30,20]])
print(matrix)
avg=matrix.mean()
print(avg)

[[10 20 30]
 [10 30 20]]
20.0


In [23]:
import numpy as np
digit=np.array(
    [
    [10,20,30],
    [15,25,12],
    [100,25,60]
    ]
)
print(digit)

[[ 10  20  30]
 [ 15  25  12]
 [100  25  60]]


In [26]:
import numpy as np
CURVE_CENTER = 80
grades = np.array([72, 35, 64, 88, 51, 90, 74, 12])
def curve(grades):
        average = grades.mean()
        change = CURVE_CENTER - average
        new_grades = grades + change
        return np.clip(new_grades, grades, 100)
curve(grades)

array([ 91.25,  54.25,  83.25, 100.  ,  70.25, 100.  ,  93.25,  31.25])

NumPy arrays can be defined using Python sequences such as lists and tuples. Lists and tuples are defined using [...] and (...), respectively. Lists and tuples can define ndarray creation:

    --> a list of numbers will create a 1D array,
    --> a list of lists will create a 2D array,
    --> further nested lists will create higher-dimensional arrays. In general, any array
        object is called an ndarray in NumPy.



In [32]:
import numpy as np
a1D=np.array([10,25,-1])
a2D=np.array([[25,7,9,10],[25,0,0,2]])
a3D=np.array([[5,2,3],[10,15,12],[25,85,2]])
print("1D array :\n",a1D,"\n")
print("2D array :\n",a2D,"\n")
print("3D array :\n",a3D,"\n")

1D array :
 [10 25 -1] 

2D array :
 [[25  7  9 10]
 [25  0  0  2]] 

3D array :
 [[ 5  2  3]
 [10 15 12]
 [25 85  2]] 



In [3]:
import numpy as np
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones(2)

array([1., 1.])

In [19]:
np.empty(3)

array([1.27847114e-316, 0.00000000e+000, 1.58101007e-322])

In [20]:
#create array with a range of element\
np.arange(5)

array([0, 1, 2, 3, 4])

In [40]:
#an array that contains a range of evenly spaced intervals. To do this,
#you will specify the first number, last number, and the step size.
print(np.arange(1,10,3))
np.arange(10,55,5)

[1 4 7]


array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [47]:
np.linspace(1,100,num=5)

array([  1,  25,  50,  75, 100])

In [49]:
np.linspace(1,50,num=5,dtype=np.int64)

array([ 1, 13, 25, 37, 50])

In [44]:
cc=np.ones(2,dtype=np.int64)
cc

array([1, 1])

[2 1 5 3 7 4 6 8]
[1 2 3 4 5 6 7 8]


In [57]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
# concatenate a and b width np.concatenate()
print("Array a :",a)
print("Array b :",b)
concate=np.concatenate((a,b))
print("Concatenate a&b :",concate)

Array a : [1 2 3 4]
Array b : [5 6 7 8]
Concatenate a&b : [1 2 3 4 5 6 7 8]


In [65]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])
x_con_y=np.concatenate((x,y),axis=0)
print(x_con_y)

[[1 2]
 [3 4]
 [5 6]]


# Sorting in numpy
    "sort", which is a quick sort.
    "argsort", which is an indirect sort along a specified axis,
    "lexsort", which is an indirect stable sort on multiple keys,
    "searchsorted", which will find elements in a sorted array, and
    "partition", which is a partial sort.
    

In [72]:
nx=np.array([10,20,30,40],dtype=np.int64)
px=np.arange(1,30,2,dtype=np.int64)
lx=np.linspace(1,50,num=5,dtype=np.int64)

In [77]:
print(nx)
print(px)
print(lx)

[10 20 30 40]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
[ 1 13 25 37 50]


# Concatenate values

In [82]:
concate_val=np.concatenate((nx,px,lx))
print("Concatenate of nx , px , lx is:\n",concate_val)

Concatenate of nx , px , lx is:
 [10 20 30 40  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29  1 13 25 37 50]


In [84]:
# now am going to sort the concatenate values using diff. kind of sorting technique
#quick sort
sort_quick = np.sort(concate_val)
print(concate_val,"\nQuick Sort :\n",sort_quick)

[10 20 30 40  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29  1 13 25 37 50] 
Quick Sort :
 [ 1  1  3  5  7  9 10 11 13 13 15 17 19 20 21 23 25 25 27 29 30 37 40 50]


In [86]:
# numpy.argsort(a, axis=-1, kind=None, order=None)
arg_sort = np.argsort(concate_val)
print(arg_sort)

[19  4  5  6  7  8  0  9 20 10 11 12 13  1 14 15 16 21 17 18  2 22  3 23]


In [97]:
# Two-dimensional array:
x = np.array([[0, 3], [2, 2]])
print("original 2D array :\n",x)
ind=np.argsort(x,axis=0)
print("arg sort 2D array :\n",ind)
take_axis=np.take_along_axis(x, ind, axis=0)
print("take_along_axis :\n",take_axis)

original 2D array :
 [[0 3]
 [2 2]]
arg sort 2D array :
 [[0 1]
 [1 0]]
take_along_axis :
 [[0 2]
 [2 3]]


In [98]:
np.sort_complex([5, 3, 6, 2, 1])


array([1.+0.j, 2.+0.j, 3.+0.j, 5.+0.j, 6.+0.j])

In [99]:
np.sort_complex([1 + 2j, 2 - 1j, 3 - 2j, 3 - 3j, 3 + 5j])

array([1.+2.j, 2.-1.j, 3.-3.j, 3.-2.j, 3.+5.j])

# precept

In [6]:
import numpy as np
arr1D = np.array([20,30,5])
arr2D = np.array([[20,8,10],[5,25,12]])
arr3D = np.array([[50,-10,3],[25,15,6],[100,20,10]])
print(arr1D)
print()
print(arr2D)
print()
print(arr3D)

[20 30  5]

[[20  8 10]
 [ 5 25 12]]

[[ 50 -10   3]
 [ 25  15   6]
 [100  20  10]]


In [10]:
# Concatenate
con_arr =  np.concatenate((arr1D,arr2D,arr3D))
#it shows error cz dimention of 1D 2D 3D array are different
#if we concate we must use the same dimention array
print(con_arr)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [14]:
con_1D = np.concatenate((arr1D,arr1D))
print("1D array concatenate :",con_1D)

1D array concatenate : [20 30  5 20 30  5]


In [19]:
con_2D = np.concatenate((arr2D,arr2D))
con_3D = np.concatenate((arr3D,arr3D))
print("2D array concatenate :\n",con_2D)
print("3D array concatenate :\n",con_3D)

2D array concatenate :
 [[20  8 10]
 [ 5 25 12]
 [20  8 10]
 [ 5 25 12]]
3D array concatenate :
 [[ 50 -10   3]
 [ 25  15   6]
 [100  20  10]
 [ 50 -10   3]
 [ 25  15   6]
 [100  20  10]]


# Sorting

In [26]:
print("array :",con_1D)
sort_1D = np.sort(con_1D)
print("sorted array :",sort_1D)

array : [20 30  5 20 30  5]
sorted array : [ 5  5 20 20 30 30]


In [29]:
print("array :\n",con_2D)
sort_2D = np.sort(con_2D)
print("sorted array :\n",sort_2D)

array :
 [[20  8 10]
 [ 5 25 12]
 [20  8 10]
 [ 5 25 12]]
sorted array :
 [[ 8 10 20]
 [ 5 12 25]
 [ 8 10 20]
 [ 5 12 25]]


In [32]:
print("array :\n",con_3D)
sort_3D = np.sort(con_3D)
print("Sorted array :\n",sort_3D)


array :
 [[ 50 -10   3]
 [ 25  15   6]
 [100  20  10]
 [ 50 -10   3]
 [ 25  15   6]
 [100  20  10]]
Sorted array :
 [[-10   3  50]
 [  6  15  25]
 [ 10  20 100]
 [-10   3  50]
 [  6  15  25]
 [ 10  20 100]]


# Generate basic array :
np.array()
np.zeros()
np.ones()
np.empty()
np.arange()
np.linspace()
dtype()



In [34]:
a = np.array([(10,20,30),(50,10,15),[25,80,60]])
a

array([[10, 20, 30],
       [50, 10, 15],
       [25, 80, 60]])

In [41]:
zero_arr=np.zeros(5)
zero_arr

array([0., 0., 0., 0., 0.])

In [43]:
one_arr=np.ones(3)
one_arr

array([1., 1., 1.])

The function empty creates an array whose initial content is random and depends on the state of the memory. The reason to use empty over zeros (or something similar) is speed 

In [56]:
np.empty(10)


array([2.77977765e-316, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

In [ ]:
# arange() function to create an array

In [59]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
np.arange(11,111)

array([ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,
        37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,
        50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
       102, 103, 104, 105, 106, 107, 108, 109, 110])

In [61]:
np.arange(11,111,3)

array([ 11,  14,  17,  20,  23,  26,  29,  32,  35,  38,  41,  44,  47,
        50,  53,  56,  59,  62,  65,  68,  71,  74,  77,  80,  83,  86,
        89,  92,  95,  98, 101, 104, 107, 110])

use linspace to create an array

In [64]:
np.linspace(11,111,num=11)

array([ 11.,  21.,  31.,  41.,  51.,  61.,  71.,  81.,  91., 101., 111.])

# know the shape and size of an array?

    ndarray.ndim 
        #To find the number of dimensions of the array
    ndarray.size
        #To find the total number of elements in the array
    ndarray.shape
        #to find the shape of your array


In [69]:
print(arr1D)
print("Dinension of the array : ",arr1D.ndim)

[20 30  5]
Dinension of the array :  1


In [70]:
print(arr2D)
print("Dinension of the array : ",arr2D.ndim)

[[20  8 10]
 [ 5 25 12]]
Dinension of the array :  2


In [71]:
print(arr3D)
print("Dinension of the array : ",arr3D.ndim)

[[ 50 -10   3]
 [ 25  15   6]
 [100  20  10]]
Dinension of the array :  2


In [72]:
print(arr1D)
print("Number of elements in the array : ",arr1D.size)

[20 30  5]
Number of elements in the array :  3


In [73]:
print(arr2D)
print("Number of elements in the array : ",arr2D.size)

[[20  8 10]
 [ 5 25 12]]
Number of elements in the array :  6


In [74]:
print(arr3D)
print("Number of elements in the array : ",arr3D.size)

[[ 50 -10   3]
 [ 25  15   6]
 [100  20  10]]
Number of elements in the array :  9


In [77]:
print(arr1D)
print("Number of Shape in the array : ",arr1D.shape)

[20 30  5]
Number of Shape in the array :  (3,)


In [76]:
print(arr2D)
print("Number of Shape in the array : ",arr2D.shape)

[[20  8 10]
 [ 5 25 12]]
Number of Shape in the array :  (2, 3)


In [75]:
print(arr3D)
print("Number of Shape in the array : ",arr3D.shape)

[[ 50 -10   3]
 [ 25  15   6]
 [100  20  10]]
Number of Shape in the array :  (3, 3)


In [90]:
p=np.array([[10,2,3]])
print(p.shape)

(1, 3)


In [92]:
p1=np.array([[10,2,3],[-10,2,5]])
print(p1)
print(p1.shape)

[[ 10   2   3]
 [-10   2   5]]
(2, 3)


In [97]:
p2=np.array([[100,20,10],[100,20,2],[50,6,4]])
print(p2)
print(p2.shape)

[[100  20  10]
 [100  20   2]
 [ 50   6   4]]
(3, 3)


In [104]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [105]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [106]:
array_example.size

24

In [107]:
array_example.ndim

3

In [108]:
array_example.shape

(3, 2, 4)