# reshape an array
arr.reshape()
will give a new shape to an array without changing the data

In [2]:
import numpy as np

In [22]:
a=np.arange(1,111,20)
print(a)

[  1  21  41  61  81 101]


In [25]:
b=a.reshape(2,3)
b

array([[  1,  21,  41],
       [ 61,  81, 101]])

In [14]:
c=a.reshape(3,2)
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
arr=np.array([[12,10,5]])
arr


array([[12, 10,  5]])

In [18]:
arr2 = arr[np.newaxis, :]
arr2.shape

(1, 1, 3)

In [13]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [21]:
b = np.expand_dims(a, axis=0)
b

array([[1, 2, 3, 4, 5, 6]])

In [22]:
c = np.expand_dims(a, axis=0)
c

array([[1, 2, 3, 4, 5, 6]])

# Indexing and slicing
 index and slice NumPy arrays in the same ways you can slice Python lists.

In [23]:
data = np.arange(1,7)
data

array([1, 2, 3, 4, 5, 6])

In [24]:
data[2]

3

In [25]:
data[:3]

array([1, 2, 3])

In [26]:
data[3:]

array([4, 5, 6])

In [27]:
data[2:5]

array([3, 4, 5])

In [32]:
a = np.array([[5, 6, 7, 8],[1 , 2, 3, 4],[9, 10, 11, 12]])
print(a)

[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]


In [36]:
p=a[a<10]
sorted(p)

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
eight_up = (a >= 5)
print(eight_up)

[[ True  True  True  True]
 [False False False False]
 [ True  True  True  True]]


In [38]:
print(a[eight_up])

[ 5  6  7  8  9 10 11 12]


In [42]:
divisible_by_2=(a%2==0)
divisible_by_2

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [40]:
print(divisible_by_2)

[ 6  8  2  4 10 12]


In [44]:
c = a[(a > 2) & (a < 11)]
c

array([ 5,  6,  7,  8,  3,  4,  9, 10])

In [45]:
print(c)

[ 5  6  7  8  3  4  9 10]


In [46]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[ True  True  True  True]
 [False False False False]
 [ True  True  True  True]]


In [47]:
a=np.array([1,2,3,4])
a.sum()

10

In [49]:
b=np.array([[1,1],[2,3]])
b.sum(axis=0)


array([3, 4])