In [1]:
import numpy as np
import numpy as pd

In [2]:
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [3]:
print("1D \n",a1D)
print("2D \n",a2D)
print("3D \n",a3D)

1D 
 [1 2 3 4]
2D 
 [[1 2]
 [3 4]]
3D 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
a = np.array([127, 128, 129])
a

array([127, 128, 129])

In [8]:
print('unsigned c:', c_unsigned32, c_unsigned32.dtype)


NameError: name 'c_unsigned32' is not defined

# linspace
np.linspace(start,end,total_number)

In [11]:

np.linspace(1., 4., 6)
 

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [13]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])